import { StaffMember } from "@/lib/types";

export function staffToBackend(staff: StaffMember | Omit<StaffMember, 'id'>): Record<string, unknown> {
  return {
    ...(('id' in staff) && { id: staff.id }),
    company_id: staff.companyId,
    user_id: staff.userId,
    first_name: staff.firstName,
    last_name: staff.lastName,
    staff_number: staff.staffNumber,
    email: staff.email,
    phone: staff.phone,
    rssb_number: staff.rssbNumber,
    employee_category: staff.employeeCategory,
    gender: staff.gender,
    birth_date: staff.birthDate,
    department: staff.department,
    position: staff.position,
    employment_date: staff.employmentDate,
    termination_date: staff.terminationDate,
    nationality: staff.nationality,
    national_id_number: staff.nationalIdNumber,
    passport_number: staff.passportNumber,
    province: staff.province,
    district: staff.district,
    sector: staff.sector,
    cell: staff.cell,
    village: staff.village,
    bank_name: staff.bankName,
    bank_account_number: staff.bankAccountNumber,
    emergency_contact_name: staff.emergencyContactName,
    emergency_contact_relationship: staff.emergencyContactRelationship,
    emergency_contact_phone: staff.emergencyContactPhone,
    status: staff.status,
    custom_fields: staff.customFields,
  };
}

export function staffFromBackend(staff: Record<string, any>): StaffMember {
  return {
    id: staff.id,
    companyId: staff.company_id,
    userId: staff.user_id,
    firstName: staff.first_name,
    lastName: staff.last_name,
    staffNumber: staff.staff_number,
    email: staff.email,
    phone: staff.phone,
    rssbNumber: staff.rssb_number,
    employeeCategory: staff.employee_category,
    gender: staff.gender,
    birthDate: staff.birth_date,
    department: staff.department,
    position: staff.position,
    employmentDate: staff.employment_date,
    terminationDate: staff.termination_date,
    nationality: staff.nationality,
    nationalIdNumber: staff.national_id_number,
    passportNumber: staff.passport_number,
    province: staff.province,
    district: staff.district,
    sector: staff.sector,
    cell: staff.cell,
    village: staff.village,
    bankName: staff.bank_name,
    bankAccountNumber: staff.bank_account_number,
    emergencyContactName: staff.emergency_contact_name,
    emergencyContactRelationship: staff.emergency_contact_relationship,
    emergencyContactPhone: staff.emergency_contact_phone,
    status: staff.status,
    customFields: staff.custom_fields,
  };
}
