import { StaffMember } from "@/lib/types";

export function staffToBackend(staff: StaffMember | Omit<StaffMember, 'id'>): Record<string, unknown> {
  return {
    ...(('id' in staff) && { id: staff.id }),
    company_id: staff.companyId,
    staff_number: staff.staffNumber,
    first_name: staff.firstName,
    last_name: staff.lastName,
    email: staff.email,
    phone: staff.phone,
    staff_rssb_number: staff.staffRssbNumber,
    employee_category: staff.employeeCategory,
    gender: staff.gender,
    birth_date: staff.birthDate,
    department: staff.department,
    designation: staff.designation,
    employment_date: staff.employmentDate,
    nationality: staff.nationality,
    id_passport_number: staff.idPassportNumber,
    province: staff.province,
    district: staff.district,
    sector: staff.sector,
    cell: staff.cell,
    village: staff.village,
    bank_name: staff.bankName,
    bank_code: staff.bankCode,
    bank_account_number: staff.bankAccountNumber,
    bank_branch: staff.bankBranch,
    key_contact_name: staff.keyContactName,
    key_contact_relationship: staff.keyContactRelationship,
    key_contact_phone: staff.keyContactPhone,
    status: staff.status,
    custom_fields: staff.customFields,
  };
}

export function staffFromBackend(staff: Record<string, unknown>): StaffMember {
  return {
    id: staff.id,
    companyId: staff.company_id,
    staffNumber: staff.staff_number,
    firstName: staff.first_name,
    lastName: staff.last_name,
    email: staff.email,
    phone: staff.phone,
    staffRssbNumber: staff.staff_rssb_number,
    employeeCategory: staff.employee_category,
    gender: staff.gender,
    birthDate: staff.birth_date,
    department: staff.department,
    designation: staff.designation,
    employmentDate: staff.employment_date,
    nationality: staff.nationality,
    idPassportNumber: staff.id_passport_number,
    province: staff.province,
    district: staff.district,
    sector: staff.sector,
    cell: staff.cell,
    village: staff.village,
    bankName: staff.bank_name,
    bankCode: staff.bank_code,
    bankAccountNumber: staff.bank_account_number,
    bankBranch: staff.bank_branch,
    keyContactName: staff.key_contact_name,
    keyContactRelationship: staff.key_contact_relationship,
    keyContactPhone: staff.key_contact_phone,
    status: staff.status,
    customFields: staff.custom_fields,
  };
}
